### ISSUE TITLE
 Actividad 4 

### ISSUE THREAD

**Issue by PedroGarcia11439** [SistemasTecTlaxiaco/actividad-4-mapa-mental-PedroGarcia11439#1]
Actividad 4 
Mapa mental 
1BS
Pedro García García
[Comunicación Oral Y Escrita.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-PedroGarcia11439/files/9613117/Comunicacion.Oral.Y.Escrita.pdf)

**Comment by josealfredo79** [comment]
Calificacion 18

**Comment by josealfredo79** [comment]
Bien hecho y revisado
